name: Publish SUD

on:
  push:
    tags:
        - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Linting
      run: |
        ruff check .
    - name: Testing
      run: |
        pytest
    - name: Get the version
      id: get_version
      run: echo  "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry version ${{ steps.get_version.outputs.VERSION }}
        poetry build
        poetry publish -u $TWINE_USERNAME -p $TWINE_PASSWORD
